### ISSUE TITLE
Version Check for Safari Appears to be Broken

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/system-requirements-check#2]
Hello, as we discussed on Slack, it looks like the version check for Safari is not working with versions 10 and above.

![screen shot 2016-11-14 at 2 48 55 pm](https://cloud.githubusercontent.com/assets/237349/20282448/50f55f98-aa7a-11e6-9810-743aa00d8abc.png)

The warnings/errors for ~~Java and~~ (#3) Flash are expected behavior based on how my system/Safari is configured.

**Comment by Lin87** [comment]
Fixed. I was comparing version number in string instead of integer value. Apparently, "6" is greater than "10".
